Day.create(name: "Lunes", code: "M")
Day.create(name: "Martes", code: "T")
Day.create(name: "Miércoles", code: "W")
Day.create(name: "Jueves", code: "R")
Day.create(name: "Viernes", code: "F")
Day.create(name: "Sábado", code: "S")
Day.create(name: "Domingo", code: "U")
